name: flutter_web_demo
description: An app built using Flutter for web

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: ^0.12.0+2
  built_collection: ^4.2.2
  built_value: ^6.5.0

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  built_value_generator: ^6.4.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui