name: flutter_web_demo
description: App built using Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.2
  built_value: ^7.0.4
  http: ^0.12.0+3

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.2
  built_value_generator: ^7.0.4
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - icons/left_arrow.png
